version: '3'
services:
#  seq:
#    image: datalust/seq:latest
#    ports:
#      - "5341:5341"
#    environment:
#      ACCEPT_EULA: Y
#    restart: unless-stopped
#    volumes:
#      - ./seq-data:/data
  sts:
    build:
      context: ./STS.Api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production 