version: '3'
services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./seq-data:/data
  sts:
    build:
      context: C:\Users\user\Documents\Repositories\StudentTestingSystemBack\STS.Api #/STS.Api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production 