global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'stsApi'
    scrape_interval: 5s
    static_configs:
      - targets: [10.1.0.4:2248]
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.1.0.4:8070
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ] 
    static_configs:
      - targets:
        - 10.1.0.4:2248/api/HealthCheck
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 10.1.0.4:9115